### PR TITLE
Remove `squash` from command list

### PR DESCRIPTION
**Pull request by Nilstrieb**
Squash is hopelessly broken and should never be used. (#136, #181).

### CODE REVIEW

**Review by jyn514 — APPROVED** [review]
seems good, although maybe we should say "unsupported" or something like that instead?

**Comment by Mark-Simulacrum** [comment]
Can we adjust the code to not run it as well, if that hasn't been done yet?

**Comment by Nilstrieb** [comment]
That sounds reasonable as well, I think disabling it like this should hopefully not break anything and safely disable it (hopefully).

**Comment by Nilstrieb** [comment]
@Mark-Simulacrum seems like you forgot about this

**Pull request merged**
