### PR TITLE
Document `squash` and `squash-` commands

### PR DESCRIPTION
**Pull request by kellda**
Document commands introduced in #122

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Can we give an example of what the squashed commit looks like (i.e., in terms of commit message)? Is it the automated commit message git produces?

If  there's a chance we can steal the text of the PR description that would be amazing I think.

**Comment by kellda** [comment]
The text is the same as if someone made it with `rebase -i`, i.e.
```
commit message 1

commit message 2

commit message 3

...
```

**Comment by Mark-Simulacrum** [comment]
I think that's *almost never* what I want from an automated squash FWIW -- maybe we can use git's "fixup" rather than "squash" flow to get the first commit message?

**Comment by kellda** [comment]
Then using `git reset --soft` then `commit -m` may be easier. Using a custom editor is only needed to keep commit messages

**Comment by kellda** [comment]
So here are the alternatives I see for the commit message:
* message of all commits
* message of first or last commit
* something with issue number, title, and/or body (like merge commits)
* only the merge commit (`git merge --squash`)
* custom message given with the rebase command

**Comment by Mark-Simulacrum** [comment]
I think pulling issue title as the summary line and body as the body, potentially wrapped to 80 characters, would be my preference.

**Comment by kellda** [comment]
Ok, I was just wondering whether there's somthing more useful to include since PR title and body are already included in the memge commit.

Sould I add this in this PR or make another one ?

**Comment by Mark-Simulacrum** [comment]
I think it's fine to expand this PR. The reason I suggest PR title and body is because those are easily adjustable on the web UI.

**Comment by kellda** [comment]
(I've implemented these changes)

**Comment by Mark-Simulacrum** [comment]
@pietroalbini -- would you be up for reviewing that last commit? It seems good to me but I don't currently have a setup locally to test things out

**Comment by pietroalbini** [comment]
Confirmed locally that it works!

**Pull request merged**
